sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.4.4
  - ghc: 8.6.4
  - ghc: 8.8.1

install:
  - cabal update
  - cabal build --enable-tests --enable-benchmarks --write-ghc-environment-files=always

script:
  - cabal test --enable-tests

notifications:
  email: false
